//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APTEventsEntities : DbContext
    {
        public APTEventsEntities()
            : base("name=APTEventsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventBooking> EventBooking { get; set; }
        public virtual DbSet<EventBookingSeat> EventBookingSeat { get; set; }
        public virtual DbSet<EventPerformance> EventPerformance { get; set; }
        public virtual DbSet<EventVenueZone> EventVenueZone { get; set; }
        public virtual DbSet<Venue> Venue { get; set; }
        public virtual DbSet<VenueType> VenueType { get; set; }
        public virtual DbSet<VenueZone> VenueZone { get; set; }
        public virtual DbSet<Category> Category { get; set; }
    }
}
