//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventBookingSeat
    {
        public int EventBookingSeat_ID { get; set; }
        public Nullable<int> EventBookingSeat_EventBookingID { get; set; }
        public string EventBookingSeat_SeatIdentifier { get; set; }
        public bool EventBookingSeat_Deleted { get; set; }
    
        public virtual EventBooking EventBooking { get; set; }
    }
}
