//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventVenueZone
    {
        public int EventVenueZone_ID { get; set; }
        public Nullable<int> EventVenueZone_EventID { get; set; }
        public Nullable<int> EventVenueZone_VenueZoneID { get; set; }
        public Nullable<int> EventVenueZone_Price { get; set; }
        public bool EventVenueZone_Deleted { get; set; }
    
        public virtual VenueZone VenueZone { get; set; }
        public virtual Event Event { get; set; }
    }
}
