//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPerformance
    {
        public EventPerformance()
        {
            this.EventBooking = new HashSet<EventBooking>();
        }
    
        public int EventPerformance_ID { get; set; }
        public Nullable<int> EventPerformance_EventID { get; set; }
        public Nullable<System.DateTime> EventPerformance_Date { get; set; }
        public Nullable<System.TimeSpan> EventPerformance_Time { get; set; }
        public bool EventPerformance_Deleted { get; set; }
    
        public virtual ICollection<EventBooking> EventBooking { get; set; }
        public virtual Event Event { get; set; }
    }
}
