//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.EventBooking = new HashSet<EventBooking>();
        }
    
        public int User_ID { get; set; }
        public string User_Login { get; set; }
        public string User_Password { get; set; }
        public string User_Name { get; set; }
        public string User_Surname { get; set; }
        public string User_Email { get; set; }
        public string User_Mobile { get; set; }
        public Nullable<System.DateTime> User_DOB { get; set; }
        public Nullable<int> User_RoleID { get; set; }
        public bool User_Deleted { get; set; }
    
        public virtual ICollection<EventBooking> EventBooking { get; set; }
        public virtual Role Role { get; set; }
    }
}
