//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueZone
    {
        public VenueZone()
        {
            this.EventVenueZone = new HashSet<EventVenueZone>();
        }
    
        public int VenueZone_ID { get; set; }
        public string VenueZone_Name { get; set; }
        public int VenueZone_VenueID { get; set; }
        public string VenueZone_Code { get; set; }
        public int VenueZone_Rows { get; set; }
        public int VenueZone_Columns { get; set; }
        public bool VenueZone_Deleted { get; set; }
    
        public virtual ICollection<EventVenueZone> EventVenueZone { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
