//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Event = new HashSet<Event>();
            this.VenueZone = new HashSet<VenueZone>();
        }
    
        public int Venue_ID { get; set; }
        public string Venue_Name { get; set; }
        public Nullable<int> Venue_VenueTypeID { get; set; }
        public Nullable<int> Venue_Capacity { get; set; }
        public string Venue_Address { get; set; }
        public bool Venue_Deleted { get; set; }
    
        public virtual VenueType VenueType { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<VenueZone> VenueZone { get; set; }
    }
}
