//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEventAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueType
    {
        public VenueType()
        {
            this.Venue = new HashSet<Venue>();
        }
    
        public int VenueType_ID { get; set; }
        public string VenueType_Name { get; set; }
        public bool VenueType_Deleted { get; set; }
    
        public virtual ICollection<Venue> Venue { get; set; }
    }
}
